services:
  - type: web
    name: real-bank-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: API_UPSTREAM
        value: http://127.0.0.1:8081
    healthCheckPath: /
    previews:
      generation: automatic
